name: dif_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _pytorch_select=0.1=cpu_0
  - absl-py=0.15.0=pyhd8ed1ab_0
  - aiohttp=3.7.4.post0=py39h89e85a6_0
  - argh=0.26.2=pyh9f0ad1d_1002
  - async-timeout=3.0.1=py_1000
  - attrs=21.2.0=pyhd8ed1ab_0
  - blas=1.0=mkl
  - blinker=1.4=py_1
  - brotli=1.0.9=hb1e8313_2
  - brotlipy=0.7.0=py39h89e85a6_1001
  - c-ares=1.18.1=h0d85af4_0
  - ca-certificates=2021.10.8=h033912b_0
  - cachetools=4.2.4=pyhd8ed1ab_0
  - certifi=2021.10.8=py39h6e9494a_0
  - cffi=1.14.6=py39h2125817_0
  - chardet=4.0.0=py39h6e9494a_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=8.0.3=py39h6e9494a_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - configparser=5.0.2=pyhd8ed1ab_0
  - cryptography=35.0.0=py39h209aa08_1
  - cycler=0.10.0=py39hecd8cb5_0
  - dataclasses=0.8=pyhc8e2a94_3
  - docker-pycreds=0.4.0=py_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=hd8bbffd_0
  - fsspec=2021.10.1=pyhd8ed1ab_0
  - future=0.18.2=py39h6e9494a_3
  - giflib=5.2.1=haf1e3a3_0
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.24=pyhd8ed1ab_0
  - google-auth=1.35.0=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - gql=0.1.0=py_0
  - graphql-core=3.1.6=pyhd8ed1ab_0
  - grpcio=1.37.1=py39hb974310_0
  - idna=3.1=pyhd3deb0d_0
  - importlib-metadata=4.8.1=py39h6e9494a_0
  - intel-openmp=2019.4=233
  - jpeg=9d=h9ed2024_0
  - kiwisolver=1.3.1=py39h23ab428_0
  - lcms2=2.12=hf1fd2bf_0
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.3=hb1e8313_2
  - libmklml=2019.0.5=0
  - libpng=1.6.37=ha441bb4_0
  - libprotobuf=3.15.8=hcf210ce_1
  - libtiff=4.2.0=h87d7836_0
  - libwebp=1.2.0=hacca55c_0
  - libwebp-base=1.2.0=h9ed2024_0
  - llvm-openmp=12.0.0=h0dcd299_1
  - lz4-c=1.9.3=h23ab428_1
  - markdown=3.3.4=pyhd8ed1ab_0
  - matplotlib=3.4.3=py39hecd8cb5_0
  - matplotlib-base=3.4.3=py39h0a11d32_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py39h9ed2024_0
  - mkl_fft=1.3.0=py39ha059aab_0
  - mkl_random=1.0.2=py39h16bde0e_0
  - multidict=5.2.0=py39h89e85a6_0
  - munkres=1.1.4=py_0
  - ncurses=6.2=h0a44026_1
  - ninja=1.10.2=hf7b0b51_1
  - numpy=1.19.2=py39he57783f_0
  - numpy-base=1.19.2=py39hde55871_0
  - nvidia-ml=7.352.0=py_0
  - oauthlib=3.1.1=pyhd8ed1ab_0
  - olefile=0.46=pyhd3eb1b0_0
  - openssl=1.1.1l=h0d85af4_0
  - packaging=21.2=pyhd8ed1ab_1
  - pathtools=0.1.2=py_1
  - pillow=8.4.0=py39h98e4679_0
  - pip=21.2.4=py39hecd8cb5_0
  - promise=2.3=py39h6e9494a_4
  - protobuf=3.15.8=py39h9fcab8e_0
  - psutil=5.8.0=py39h89e85a6_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_2
  - pydeprecate=0.3.1=pyhd8ed1ab_0
  - pyjwt=2.3.0=pyhd8ed1ab_0
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pysocks=1.7.1=py39h6e9494a_3
  - python=3.9.7=h88f2d9e_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=1.7.1=cpu_py39h7e2095a_0
  - pytorch-lightning=1.4.9=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py39h89e85a6_0
  - readline=8.1=h9ed2024_0
  - requests=2.26.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.7.2=pyh44b312d_0
  - sentry-sdk=1.4.3=pyhd8ed1ab_0
  - setuptools=58.0.4=py39hecd8cb5_0
  - shortuuid=1.0.1=py39h6e9494a_4
  - six=1.16.0=pyhd3eb1b0_0
  - smmap=3.0.5=pyh44b312d_0
  - sqlite=3.36.0=hce871da_0
  - subprocess32=3.5.4=py_1
  - tensorboard=2.6.0=pyhd8ed1ab_1
  - tensorboard-data-server=0.6.0=py39h4b466c7_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - tk=8.6.11=h7bc2e8c_0
  - torchmetrics=0.6.0=pyhd8ed1ab_0
  - tornado=6.1=py39h9ed2024_0
  - tqdm=4.62.3=pyhd8ed1ab_0
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - tzdata=2021e=hda174b7_0
  - urllib3=1.26.7=pyhd8ed1ab_0
  - wandb=0.12.1=pyhd8ed1ab_0
  - watchdog=0.10.4=py39h4059872_0
  - werkzeug=2.0.1=pyhd8ed1ab_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h1de35cc_0
  - yaml=0.2.5=haf1e3a3_0
  - yarl=1.7.0=py39h89e85a6_0
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.9=h322a384_0
  - pip:
    - earthnet==0.2.3
    - fire==0.4.0
    - imageio==2.10.1
    - networkx==2.6.3
    - pandas==1.3.4
    - pyproj==3.2.1
    - pytz==2021.3
    - pywavelets==1.1.1
    - scikit-image==0.18.3
    - scipy==1.7.1
    - termcolor==1.1.0
    - tifffile==2021.10.12
prefix: /Users/marcomilanta/miniconda3/envs/dif_env
